import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";
import { ISliderCard, IExplores } from "../types/Home";

type Props = {
  explores: IExplores[],
  sliderCards: ISliderCard[]
}

const Home: NextPage<Props> = ({ explores = [], sliderCards = [] }) => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Banner */}
      <Banner />

      {/* Main */}
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {explores.map((item: IExplores, i) => (
              <SmallCard key={i} {...item} />
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>

          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {sliderCards.map((card: ISliderCard, i) => (
              <MediumCard key={i} {...card} />
            ))}
          </div>
        </section>

        <LargeCard 
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoor" 
          description="Wishlists curated by Airbnb"
          btnText="Get Inspired"
        />
      </main>

      <Footer />
    </div>
  );
}

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const explores: IExplores[] = await fetch("https://links.papareact.com/pyp")
    .then((res) => res.json());

  const sliderCards: ISliderCard[] = await fetch("https://links.papareact.com/zp1")
    .then((res) => res.json());

  return {
    props: {
      explores,
      sliderCards
    }
  }
}